// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: cientifics_works.sql

package db

import (
	"context"
)

const createCientificWork = `-- name: CreateCientificWork :one
INSERT INTO cientifics_works(title, author_id, inscription_id, resume, file, presentation_type, exposition_type) 
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations
`

type CreateCientificWorkParams struct {
	Title            string `json:"title"`
	AuthorID         int32  `json:"author_id"`
	InscriptionID    int32  `json:"inscription_id"`
	Resume           string `json:"resume"`
	File             string `json:"file"`
	PresentationType string `json:"presentation_type"`
	ExpositionType   string `json:"exposition_type"`
}

func (q *Queries) CreateCientificWork(ctx context.Context, arg CreateCientificWorkParams) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, createCientificWork,
		arg.Title,
		arg.AuthorID,
		arg.InscriptionID,
		arg.Resume,
		arg.File,
		arg.PresentationType,
		arg.ExpositionType,
	)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}

const deleteCientificWork = `-- name: DeleteCientificWork :exec

DELETE FROM cientifics_works
WHERE id = $1
`

// #Pendig Event filter
func (q *Queries) DeleteCientificWork(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCientificWork, id)
	return err
}

const getCientificWork = `-- name: GetCientificWork :one
SELECT id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations FROM cientifics_works
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCientificWork(ctx context.Context, id int64) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, getCientificWork, id)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}

const getCientificWorkAdmitted = `-- name: GetCientificWorkAdmitted :one
SELECT id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations FROM cientifics_works WHERE (id = $1 AND admitted = true) LIMIT 1
`

func (q *Queries) GetCientificWorkAdmitted(ctx context.Context, id int64) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, getCientificWorkAdmitted, id)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}

const getCientificWorkByAuthorId = `-- name: GetCientificWorkByAuthorId :many
SELECT id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations FROM cientifics_works
WHERE author_id = $1
LIMIT $2
OFFSET $3
`

type GetCientificWorkByAuthorIdParams struct {
	AuthorID int32 `json:"author_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) GetCientificWorkByAuthorId(ctx context.Context, arg GetCientificWorkByAuthorIdParams) ([]CientificsWork, error) {
	rows, err := q.db.QueryContext(ctx, getCientificWorkByAuthorId, arg.AuthorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CientificsWork{}
	for rows.Next() {
		var i CientificsWork
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.InscriptionID,
			&i.Resume,
			&i.File,
			&i.PresentationType,
			&i.ExpositionType,
			&i.CreatedAt,
			&i.Admitted,
			&i.Recommendations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCientificWorks = `-- name: ListCientificWorks :many
SELECT id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations FROM cientifics_works
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCientificWorksParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCientificWorks(ctx context.Context, arg ListCientificWorksParams) ([]CientificsWork, error) {
	rows, err := q.db.QueryContext(ctx, listCientificWorks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CientificsWork{}
	for rows.Next() {
		var i CientificsWork
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.InscriptionID,
			&i.Resume,
			&i.File,
			&i.PresentationType,
			&i.ExpositionType,
			&i.CreatedAt,
			&i.Admitted,
			&i.Recommendations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCientificsWorksAdmitted = `-- name: ListCientificsWorksAdmitted :one
SELECT id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations FROM cientifics_works WHERE (admitted = true) LIMIT 1
`

func (q *Queries) ListCientificsWorksAdmitted(ctx context.Context) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, listCientificsWorksAdmitted)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}

const setCientificWorkAdmitted = `-- name: SetCientificWorkAdmitted :one
UPDATE cientifics_works
  set admitted=$2
WHERE id = $1 RETURNING id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations
`

type SetCientificWorkAdmittedParams struct {
	ID       int64 `json:"id"`
	Admitted bool  `json:"admitted"`
}

func (q *Queries) SetCientificWorkAdmitted(ctx context.Context, arg SetCientificWorkAdmittedParams) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, setCientificWorkAdmitted, arg.ID, arg.Admitted)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}

const setCientificWorkRecomendations = `-- name: SetCientificWorkRecomendations :one
UPDATE cientifics_works
  set recommendations=$2
WHERE id = $1 RETURNING id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations
`

type SetCientificWorkRecomendationsParams struct {
	ID              int64  `json:"id"`
	Recommendations string `json:"recommendations"`
}

func (q *Queries) SetCientificWorkRecomendations(ctx context.Context, arg SetCientificWorkRecomendationsParams) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, setCientificWorkRecomendations, arg.ID, arg.Recommendations)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}

const updateCientificWork = `-- name: UpdateCientificWork :one
UPDATE cientifics_works
  set title = $2, author_id = $3, resume = $4, file = $5, presentation_type = $6, exposition_type = $7, inscription_id = $8
WHERE id = $1 RETURNING id, title, author_id, inscription_id, resume, file, presentation_type, exposition_type, created_at, admitted, recommendations
`

type UpdateCientificWorkParams struct {
	ID               int64  `json:"id"`
	Title            string `json:"title"`
	AuthorID         int32  `json:"author_id"`
	Resume           string `json:"resume"`
	File             string `json:"file"`
	PresentationType string `json:"presentation_type"`
	ExpositionType   string `json:"exposition_type"`
	InscriptionID    int32  `json:"inscription_id"`
}

func (q *Queries) UpdateCientificWork(ctx context.Context, arg UpdateCientificWorkParams) (CientificsWork, error) {
	row := q.db.QueryRowContext(ctx, updateCientificWork,
		arg.ID,
		arg.Title,
		arg.AuthorID,
		arg.Resume,
		arg.File,
		arg.PresentationType,
		arg.ExpositionType,
		arg.InscriptionID,
	)
	var i CientificsWork
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.InscriptionID,
		&i.Resume,
		&i.File,
		&i.PresentationType,
		&i.ExpositionType,
		&i.CreatedAt,
		&i.Admitted,
		&i.Recommendations,
	)
	return i, err
}
