// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: event.sql

package db

import (
	"context"
	"time"
)

const activeEvent = `-- name: ActiveEvent :one
SELECT id, name, init_date, end_date, active, created_at FROM events WHERE active = true
`

func (q *Queries) ActiveEvent(ctx context.Context) (Event, error) {
	row := q.db.QueryRowContext(ctx, activeEvent)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InitDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events(name, init_date, end_date) 
VALUES ($1, $2, $3) RETURNING id, name, init_date, end_date, active, created_at
`

type CreateEventParams struct {
	Name     string    `json:"name"`
	InitDate time.Time `json:"init_date"`
	EndDate  time.Time `json:"end_date"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.Name, arg.InitDate, arg.EndDate)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InitDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, init_date, end_date, active, created_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InitDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, name, init_date, end_date, active, created_at FROM events
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.InitDate,
			&i.EndDate,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
  set name = $2, init_date = $3, end_date = $4, created_at = now()
WHERE id = $1 RETURNING id, name, init_date, end_date, active, created_at
`

type UpdateEventParams struct {
	ID       int64     `json:"id"`
	Name     string    `json:"name"`
	InitDate time.Time `json:"init_date"`
	EndDate  time.Time `json:"end_date"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.ID,
		arg.Name,
		arg.InitDate,
		arg.EndDate,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.InitDate,
		&i.EndDate,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
