// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: inscription.sql

package db

import (
	"context"
	"database/sql"
)

const createInscription = `-- name: CreateInscription :one
INSERT INTO inscriptions(user_id, event_id) 
VALUES ($1, $2) RETURNING id, user_id, event_id, created_at
`

type CreateInscriptionParams struct {
	UserID  int32 `json:"user_id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) CreateInscription(ctx context.Context, arg CreateInscriptionParams) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, createInscription, arg.UserID, arg.EventID)
	var i Inscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInscription = `-- name: DeleteInscription :exec
DELETE FROM inscriptions
WHERE id = $1
`

func (q *Queries) DeleteInscription(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInscription, id)
	return err
}

const findInscription = `-- name: FindInscription :one
SELECT id, user_id, event_id, created_at FROM inscriptions
WHERE (user_id = $1 AND event_id = $2) LIMIT 1
`

type FindInscriptionParams struct {
	UserID  int32 `json:"user_id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) FindInscription(ctx context.Context, arg FindInscriptionParams) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, findInscription, arg.UserID, arg.EventID)
	var i Inscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const getInscription = `-- name: GetInscription :one
SELECT id, user_id, event_id, created_at FROM inscriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInscription(ctx context.Context, id int64) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, getInscription, id)
	var i Inscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}

const listDetailsInscriptions = `-- name: ListDetailsInscriptions :many
SELECT inscriptions.id, inscriptions.created_at, users.name, users.last_name, cientifics_works.title as work_title, events.name as event
FROM inscriptions
  INNER JOIN users ON inscriptions.user_id = users.id
  INNER JOIN cientifics_works ON inscriptions.id = cientifics_works.inscription_id
  INNER JOIN events ON inscriptions.event_id = events.id
ORDER BY 
  inscriptions.created_at
LIMIT $1
OFFSET $2
`

type ListDetailsInscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDetailsInscriptionsRow struct {
	ID        int64        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	Name      string       `json:"name"`
	LastName  string       `json:"last_name"`
	WorkTitle string       `json:"work_title"`
	Event     string       `json:"event"`
}

func (q *Queries) ListDetailsInscriptions(ctx context.Context, arg ListDetailsInscriptionsParams) ([]ListDetailsInscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDetailsInscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetailsInscriptionsRow{}
	for rows.Next() {
		var i ListDetailsInscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.LastName,
			&i.WorkTitle,
			&i.Event,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInscriptions = `-- name: ListInscriptions :many
SELECT id, user_id, event_id, created_at FROM inscriptions
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListInscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInscriptions(ctx context.Context, arg ListInscriptionsParams) ([]Inscription, error) {
	rows, err := q.db.QueryContext(ctx, listInscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inscription{}
	for rows.Next() {
		var i Inscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInscription = `-- name: UpdateInscription :one
UPDATE inscriptions
  set user_id = $2, event_id = $3
WHERE id = $1 RETURNING id, user_id, event_id, created_at
`

type UpdateInscriptionParams struct {
	ID      int64 `json:"id"`
	UserID  int32 `json:"user_id"`
	EventID int32 `json:"event_id"`
}

func (q *Queries) UpdateInscription(ctx context.Context, arg UpdateInscriptionParams) (Inscription, error) {
	row := q.db.QueryRowContext(ctx, updateInscription, arg.ID, arg.UserID, arg.EventID)
	var i Inscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.CreatedAt,
	)
	return i, err
}
