// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CientificsWork struct {
	ID               int64        `json:"id"`
	Title            string       `json:"title"`
	AuthorID         int32        `json:"author_id"`
	InscriptionID    int32        `json:"inscription_id"`
	Resume           string       `json:"resume"`
	File             string       `json:"file"`
	PresentationType string       `json:"presentation_type"`
	ExpositionType   string       `json:"exposition_type"`
	CreatedAt        sql.NullTime `json:"created_at"`
	Admitted         bool         `json:"admitted"`
	Recommendations  string       `json:"recommendations"`
}

type Event struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	InitDate  time.Time    `json:"init_date"`
	EndDate   time.Time    `json:"end_date"`
	Active    bool         `json:"active"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Inscription struct {
	ID        int64        `json:"id"`
	UserID    int32        `json:"user_id"`
	EventID   int32        `json:"event_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Payment struct {
	ID               int64        `json:"id"`
	UserID           int32        `json:"user_id"`
	EventID          int32        `json:"event_id"`
	InscriptionID    int32        `json:"inscription_id"`
	UserType         string       `json:"user_type"`
	PresentationType string       `json:"presentation_type"`
	Amount           int32        `json:"amount"`
	IsPaid           bool         `json:"is_paid"`
	ProofPaymentPath string       `json:"proof_payment_path"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type PaymentRate struct {
	ID               int64        `json:"id"`
	EventID          int32        `json:"event_id"`
	UserType         string       `json:"user_type"`
	PresentationType string       `json:"presentation_type"`
	Amount           int32        `json:"amount"`
	CreatedAt        sql.NullTime `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID    `json:"id"`
	UserID       int32        `json:"user_id"`
	Email        string       `json:"email"`
	RefreshToken string       `json:"refresh_token"`
	UserAgent    string       `json:"user_agent"`
	ClientIp     string       `json:"client_ip"`
	IsBloked     bool         `json:"is_bloked"`
	ExpiredAt    time.Time    `json:"expired_at"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

type User struct {
	ID                int64        `json:"id"`
	Name              string       `json:"name"`
	LastName          string       `json:"last_name"`
	Email             string       `json:"email"`
	HashedPassword    string       `json:"hashed_password"`
	Phone             string       `json:"phone"`
	UserType          string       `json:"user_type"`
	AvatarPath        string       `json:"avatar_path"`
	PasswordChangedAt time.Time    `json:"password_changed_at"`
	CreatedAt         sql.NullTime `json:"created_at"`
	IsEmailVerified   bool         `json:"is_email_verified"`
	Role              string       `json:"role"`
}

type VerifyEmail struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	LastName   string    `json:"last_name"`
	Email      string    `json:"email"`
	UserID     int32     `json:"user_id"`
	SecretCode string    `json:"secret_code"`
	IsUsed     bool      `json:"is_used"`
	CreatedAt  time.Time `json:"created_at"`
	ExpiredAt  time.Time `json:"expired_at"`
}
