// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: payment.sql

package db

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment(user_id, event_id, user_type, presentation_type, amount, inscription_id) 
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, event_id, inscription_id, user_type, presentation_type, amount, is_paid, proof_payment_path, created_at
`

type CreatePaymentParams struct {
	UserID           int32  `json:"user_id"`
	EventID          int32  `json:"event_id"`
	UserType         string `json:"user_type"`
	PresentationType string `json:"presentation_type"`
	Amount           int32  `json:"amount"`
	InscriptionID    int32  `json:"inscription_id"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.UserID,
		arg.EventID,
		arg.UserType,
		arg.PresentationType,
		arg.Amount,
		arg.InscriptionID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.InscriptionID,
		&i.UserType,
		&i.PresentationType,
		&i.Amount,
		&i.IsPaid,
		&i.ProofPaymentPath,
		&i.CreatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payment
WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePayment, id)
	return err
}

const getPayment = `-- name: GetPayment :one
SELECT id, user_id, event_id, inscription_id, user_type, presentation_type, amount, is_paid, proof_payment_path, created_at FROM payment
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.InscriptionID,
		&i.UserType,
		&i.PresentationType,
		&i.Amount,
		&i.IsPaid,
		&i.ProofPaymentPath,
		&i.CreatedAt,
	)
	return i, err
}

const listDetailsPayments = `-- name: ListDetailsPayments :many
SELECT payment.created_at, users.name, users.last_name, events.name as event, payment.user_type as user_type, presentation_type, amount, inscription_id
FROM payment
INNER JOIN users ON payment.user_id = users.id
INNER JOIN events ON payment.event_id = events.id
ORDER BY 
  payment.created_at
LIMIT $1
OFFSET $2
`

type ListDetailsPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDetailsPaymentsRow struct {
	CreatedAt        sql.NullTime `json:"created_at"`
	Name             string       `json:"name"`
	LastName         string       `json:"last_name"`
	Event            string       `json:"event"`
	UserType         string       `json:"user_type"`
	PresentationType string       `json:"presentation_type"`
	Amount           int32        `json:"amount"`
	InscriptionID    int32        `json:"inscription_id"`
}

func (q *Queries) ListDetailsPayments(ctx context.Context, arg ListDetailsPaymentsParams) ([]ListDetailsPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDetailsPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetailsPaymentsRow{}
	for rows.Next() {
		var i ListDetailsPaymentsRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Name,
			&i.LastName,
			&i.Event,
			&i.UserType,
			&i.PresentationType,
			&i.Amount,
			&i.InscriptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayments = `-- name: ListPayments :many
SELECT id, user_id, event_id, inscription_id, user_type, presentation_type, amount, is_paid, proof_payment_path, created_at FROM payment
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPaymentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Payment{}
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventID,
			&i.InscriptionID,
			&i.UserType,
			&i.PresentationType,
			&i.Amount,
			&i.IsPaid,
			&i.ProofPaymentPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePayment = `-- name: UpdatePayment :one
UPDATE payment
  set user_id = $2, event_id = $3, user_type = $4, presentation_type = $5, amount = $6, inscription_id = $7
WHERE id = $1 RETURNING id, user_id, event_id, inscription_id, user_type, presentation_type, amount, is_paid, proof_payment_path, created_at
`

type UpdatePaymentParams struct {
	ID               int64  `json:"id"`
	UserID           int32  `json:"user_id"`
	EventID          int32  `json:"event_id"`
	UserType         string `json:"user_type"`
	PresentationType string `json:"presentation_type"`
	Amount           int32  `json:"amount"`
	InscriptionID    int32  `json:"inscription_id"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, updatePayment,
		arg.ID,
		arg.UserID,
		arg.EventID,
		arg.UserType,
		arg.PresentationType,
		arg.Amount,
		arg.InscriptionID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventID,
		&i.InscriptionID,
		&i.UserType,
		&i.PresentationType,
		&i.Amount,
		&i.IsPaid,
		&i.ProofPaymentPath,
		&i.CreatedAt,
	)
	return i, err
}
