// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: payment_rate.sql

package db

import (
	"context"
	"database/sql"
)

const getPaymentAmount = `-- name: GetPaymentAmount :one
SELECT amount FROM payment_rate WHERE (event_id = $1 AND user_type = $2 AND presentation_type = $3) LIMIT 1
`

type GetPaymentAmountParams struct {
	EventID          int32  `json:"event_id"`
	UserType         string `json:"user_type"`
	PresentationType string `json:"presentation_type"`
}

func (q *Queries) GetPaymentAmount(ctx context.Context, arg GetPaymentAmountParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getPaymentAmount, arg.EventID, arg.UserType, arg.PresentationType)
	var amount int32
	err := row.Scan(&amount)
	return amount, err
}

const listDetailsPaymentRates = `-- name: ListDetailsPaymentRates :many
SELECT payment_rate.created_at, events.name, user_type, presentation_type, amount
FROM payment_rate
INNER JOIN events ON payment_rate.event_id = events.id
LIMIT $1
OFFSET $2
`

type ListDetailsPaymentRatesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDetailsPaymentRatesRow struct {
	CreatedAt        sql.NullTime `json:"created_at"`
	Name             string       `json:"name"`
	UserType         string       `json:"user_type"`
	PresentationType string       `json:"presentation_type"`
	Amount           int32        `json:"amount"`
}

func (q *Queries) ListDetailsPaymentRates(ctx context.Context, arg ListDetailsPaymentRatesParams) ([]ListDetailsPaymentRatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDetailsPaymentRates, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDetailsPaymentRatesRow{}
	for rows.Next() {
		var i ListDetailsPaymentRatesRow
		if err := rows.Scan(
			&i.CreatedAt,
			&i.Name,
			&i.UserType,
			&i.PresentationType,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
