// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ActiveEvent(ctx context.Context) (Event, error)
	CreateCientificWork(ctx context.Context, arg CreateCientificWorkParams) (CientificsWork, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateInscription(ctx context.Context, arg CreateInscriptionParams) (Inscription, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	// #Pendig Event filter
	DeleteCientificWork(ctx context.Context, id int64) error
	DeleteEvent(ctx context.Context, id int64) error
	DeleteInscription(ctx context.Context, id int64) error
	DeletePayment(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	FindInscription(ctx context.Context, arg FindInscriptionParams) (Inscription, error)
	GetCientificWork(ctx context.Context, id int64) (CientificsWork, error)
	GetCientificWorkAdmitted(ctx context.Context, id int64) (CientificsWork, error)
	GetCientificWorkByAuthorId(ctx context.Context, arg GetCientificWorkByAuthorIdParams) ([]CientificsWork, error)
	GetEvent(ctx context.Context, id int64) (Event, error)
	GetInscription(ctx context.Context, id int64) (Inscription, error)
	GetPayment(ctx context.Context, id int64) (Payment, error)
	GetPaymentAmount(ctx context.Context, arg GetPaymentAmountParams) (int32, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserEmail(ctx context.Context, email string) (User, error)
	ListCientificWorks(ctx context.Context, arg ListCientificWorksParams) ([]CientificsWork, error)
	ListCientificsWorksAdmitted(ctx context.Context) (CientificsWork, error)
	ListDetailsInscriptions(ctx context.Context, arg ListDetailsInscriptionsParams) ([]ListDetailsInscriptionsRow, error)
	ListDetailsPaymentRates(ctx context.Context, arg ListDetailsPaymentRatesParams) ([]ListDetailsPaymentRatesRow, error)
	ListDetailsPayments(ctx context.Context, arg ListDetailsPaymentsParams) ([]ListDetailsPaymentsRow, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error)
	ListInscriptions(ctx context.Context, arg ListInscriptionsParams) ([]Inscription, error)
	ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SetCientificWorkAdmitted(ctx context.Context, arg SetCientificWorkAdmittedParams) (CientificsWork, error)
	SetCientificWorkRecomendations(ctx context.Context, arg SetCientificWorkRecomendationsParams) (CientificsWork, error)
	UpdateCientificWork(ctx context.Context, arg UpdateCientificWorkParams) (CientificsWork, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateInscription(ctx context.Context, arg UpdateInscriptionParams) (Inscription, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) (Payment, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
