// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(name, last_name, email, phone, hashed_password, user_type) 
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, last_name, email, hashed_password, phone, user_type, avatar_path, password_changed_at, created_at, is_email_verified, role
`

type CreateUserParams struct {
	Name           string `json:"name"`
	LastName       string `json:"last_name"`
	Email          string `json:"email"`
	Phone          string `json:"phone"`
	HashedPassword string `json:"hashed_password"`
	UserType       string `json:"user_type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Name,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.HashedPassword,
		arg.UserType,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.UserType,
		&i.AvatarPath,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.Role,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, last_name, email, hashed_password, phone, user_type, avatar_path, password_changed_at, created_at, is_email_verified, role FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.UserType,
		&i.AvatarPath,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.Role,
	)
	return i, err
}

const getUserEmail = `-- name: GetUserEmail :one
SELECT id, name, last_name, email, hashed_password, phone, user_type, avatar_path, password_changed_at, created_at, is_email_verified, role FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.UserType,
		&i.AvatarPath,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.Role,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, last_name, email, hashed_password, phone, user_type, avatar_path, password_changed_at, created_at, is_email_verified, role FROM users
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LastName,
			&i.Email,
			&i.HashedPassword,
			&i.Phone,
			&i.UserType,
			&i.AvatarPath,
			&i.PasswordChangedAt,
			&i.CreatedAt,
			&i.IsEmailVerified,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
  SET 
    name = $2, 
    last_name = $3, 
    email = $4, 
    phone = $5, 
    hashed_password = $6, 
    user_type = $7, 
    is_email_verified = $8,
    role = $9,
    avatar_path = $10
WHERE id = $1 RETURNING id, name, last_name, email, hashed_password, phone, user_type, avatar_path, password_changed_at, created_at, is_email_verified, role
`

type UpdateUserParams struct {
	ID              int64  `json:"id"`
	Name            string `json:"name"`
	LastName        string `json:"last_name"`
	Email           string `json:"email"`
	Phone           string `json:"phone"`
	HashedPassword  string `json:"hashed_password"`
	UserType        string `json:"user_type"`
	IsEmailVerified bool   `json:"is_email_verified"`
	Role            string `json:"role"`
	AvatarPath      string `json:"avatar_path"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.HashedPassword,
		arg.UserType,
		arg.IsEmailVerified,
		arg.Role,
		arg.AvatarPath,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.HashedPassword,
		&i.Phone,
		&i.UserType,
		&i.AvatarPath,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.IsEmailVerified,
		&i.Role,
	)
	return i, err
}
