// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: verify_email.sql

package db

import (
	"context"
)

const createVerifyEmail = `-- name: CreateVerifyEmail :one
INSERT INTO verify_emails (
  name,
  last_name,
  email,
  user_id,
  secret_code
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, last_name, email, user_id, secret_code, is_used, created_at, expired_at
`

type CreateVerifyEmailParams struct {
	Name       string `json:"name"`
	LastName   string `json:"last_name"`
	Email      string `json:"email"`
	UserID     int32  `json:"user_id"`
	SecretCode string `json:"secret_code"`
}

func (q *Queries) CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, createVerifyEmail,
		arg.Name,
		arg.LastName,
		arg.Email,
		arg.UserID,
		arg.SecretCode,
	)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.UserID,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}

const updateVerifyEmail = `-- name: UpdateVerifyEmail :one
UPDATE verify_emails 
SET
  is_used = TRUE
WHERE
  id = $1
  AND secret_code = $2
  AND is_used = FALSE
  AND expired_at > now()
RETURNING id, name, last_name, email, user_id, secret_code, is_used, created_at, expired_at
`

type UpdateVerifyEmailParams struct {
	ID         int64  `json:"id"`
	SecretCode string `json:"secret_code"`
}

func (q *Queries) UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error) {
	row := q.db.QueryRowContext(ctx, updateVerifyEmail, arg.ID, arg.SecretCode)
	var i VerifyEmail
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.LastName,
		&i.Email,
		&i.UserID,
		&i.SecretCode,
		&i.IsUsed,
		&i.CreatedAt,
		&i.ExpiredAt,
	)
	return i, err
}
